config/routes.rb
Rails.application.routes.draw do

  resources :banks
  devise_for :users #, skip: [:sessions]

  root 'welcome#index'

resources :welcome do
  member do
    get '/about_us' => 'welcome#about_us'
  end

  end
  get '/subscriptions/list/' => 'subscriptions#list', as: :list_subscription
  get '/subscriptions' => 'subscriptions#index'
  get '/subscriptions/new' => 'subscriptions#new', as: :new_subscription
  get '/subscription/:id/edit' => 'subscriptions#edit', as: :edit_subscription
  get '/subscription/:id' => 'subscriptions#show', as: :subscription
  post '/subscriptions' => 'subscriptions#create'

  get '/users/:id/dash' => 'users#dash', as: :dash_user
  get '/users/:id/profile' => 'users#profile', as: :profile_user
  get 'serve' => 'users#serve', as: :serve_photo
  resources :users do

        resources :accounts do
            member do
              get 'dash' => 'accounts#dash'
              get 'display' => 'accounts/search'
              get 'search'
            end
            resources :wallets
            resources :vaults
            resources :instants do
              resources :payments
            end
          end
      end

  resources :errors do
    member do
      get 'user'
      get 'show'
      get 'delete'
      get 'notfound'# => 'errors#notfound'

    end
  end

  get 'external_pages/about_us'
  get 'external_pages/team'
  get 'external_pages/faqs'

end

app/models/instant.rb
class Instant < ActiveRecord::Base
  belongs_to :account
  has_many :payments, dependent: :delete_all
end

app/controllers/instants_controller.rb
class InstantsController < ApplicationController
  before_action :set_user
  before_action :set_account
  before_action :set_instant, only: [:show, :edit, :update, :destroy]

  # GET /instants
  # GET /instants.json
  def index
    @instants = Instant.all
  end

  # GET /instants/1
  # GET /instants/1.json
  def show
  end

  # GET /instants/new
  def new
    @instant = @account.instants.build
  end

  # GET /instants/1/edit
  def edit
  end

  # POST /instants
  # POST /instants.json
  def create
    @instant = @account.instants.build(instant_params)

    respond_to do |format|
      if @instant.save
        format.html { redirect_to @instant, notice: 'Instant was successfully created.' }
        format.json { render :show, status: :created, location: @instant }
      else
        format.html { render :new }
        format.json { render json: @instant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instants/1
  # PATCH/PUT /instants/1.json
  def update
    respond_to do |format|
      if @instant.update(instant_params)
        format.html { redirect_to @instant, notice: 'Instant was successfully updated.' }
        format.json { render :show, status: :ok, location: @instant }
      else
        format.html { render :edit }
        format.json { render json: @instant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instants/1
  # DELETE /instants/1.json
  def destroy
    @instant.destroy
    respond_to do |format|
      format.html { redirect_to instants_url, notice: 'Instant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    respond_to do |format|
      format.html { redirect_to errors_notfound_path, notice: 'User not found.' }
      format.json { head :no_content}
    end

  end

  def set_account
    @account = Account.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    respond_to do |format|
      format.html { redirect_to errors_notfound_path, notice: 'Account not found.' }
      format.json { head :no_content}
    end
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_instant
      @instant = @account.instants.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instant_params
      params.require(:instant).permit(:Oid, :follio, :window_hours, :token_code, :date_of_confirmation, :date_of_cancelation, :device_of_cancelation, :device_of_transaction, :device_of_confirmation, :confirmed, :comment, :account_id)
    end
end

app/helpers/instants_helper.rb
module InstantsHelper
end

app/views/instants/_form.html.erb
<%= form_for(@instant) do |f| %>
  <% if @instant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instant.errors.count, "error") %> prohibited this instant from being saved:</h2>

      <ul>
      <% @instant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Oid %><br>
    <%= f.text_field :Oid %>
  </div>
  <div class="field">
    <%= f.label :follio %><br>
    <%= f.text_field :follio %>
  </div>
  <div class="field">
    <%= f.label :window_hours %><br>
    <%= f.number_field :window_hours %>
  </div>
  <div class="field">
    <%= f.label :token_code %><br>
    <%= f.text_field :token_code %>
  </div>
  <div class="field">
    <%= f.label :date_of_confirmation %><br>
    <%= f.datetime_select :date_of_confirmation %>
  </div>
  <div class="field">
    <%= f.label :date_of_cancelation %><br>
    <%= f.datetime_select :date_of_cancelation %>
  </div>
  <div class="field">
    <%= f.label :device_of_cancelation %><br>
    <%= f.text_field :device_of_cancelation %>
  </div>
  <div class="field">
    <%= f.label :device_of_transaction %><br>
    <%= f.text_field :device_of_transaction %>
  </div>
  <div class="field">
    <%= f.label :device_of_confirmation %><br>
    <%= f.text_field :device_of_confirmation %>
  </div>
  <div class="field">
    <%= f.label :confirmed %><br>
    <%= f.check_box :confirmed %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.text_field :account_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instants/edit.html.erb
<h1>Editing Instant</h1>

<%= render 'form' %>

<%= link_to 'Show', @instant %> |
<%= link_to 'Back', instants_path %>

app/views/instants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Instants</h1>

<table>
  <thead>
    <tr>
      <th>Oid</th>
      <th>Follio</th>
      <th>Window hours</th>
      <th>Token code</th>
      <th>Date of confirmation</th>
      <th>Date of cancelation</th>
      <th>Device of cancelation</th>
      <th>Device of transaction</th>
      <th>Device of confirmation</th>
      <th>Confirmed</th>
      <th>Comment</th>
      <th>Account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instants.each do |instant| %>
      <tr>
        <td><%= instant.Oid %></td>
        <td><%= instant.follio %></td>
        <td><%= instant.window_hours %></td>
        <td><%= instant.token_code %></td>
        <td><%= instant.date_of_confirmation %></td>
        <td><%= instant.date_of_cancelation %></td>
        <td><%= instant.device_of_cancelation %></td>
        <td><%= instant.device_of_transaction %></td>
        <td><%= instant.device_of_confirmation %></td>
        <td><%= instant.confirmed %></td>
        <td><%= instant.comment %></td>
        <td><%= instant.account %></td>
        <td><%= link_to 'Show', instant %></td>
        <td><%= link_to 'Edit', edit_instant_path(instant) %></td>
        <td><%= link_to 'Destroy', instant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instant', new_instant_path %>

app/views/instants/new.html.erb
<h1>New Instant</h1>

<%= render 'form' %>

<%= link_to 'Back', instants_path %>

app/views/instants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Oid:</strong>
  <%= @instant.Oid %>
</p>

<p>
  <strong>Follio:</strong>
  <%= @instant.follio %>
</p>

<p>
  <strong>Window hours:</strong>
  <%= @instant.window_hours %>
</p>

<p>
  <strong>Token code:</strong>
  <%= @instant.token_code %>
</p>

<p>
  <strong>Date of confirmation:</strong>
  <%= @instant.date_of_confirmation %>
</p>

<p>
  <strong>Date of cancelation:</strong>
  <%= @instant.date_of_cancelation %>
</p>

<p>
  <strong>Device of cancelation:</strong>
  <%= @instant.device_of_cancelation %>
</p>

<p>
  <strong>Device of transaction:</strong>
  <%= @instant.device_of_transaction %>
</p>

<p>
  <strong>Device of confirmation:</strong>
  <%= @instant.device_of_confirmation %>
</p>

<p>
  <strong>Confirmed:</strong>
  <%= @instant.confirmed %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @instant.comment %>
</p>

<p>
  <strong>Account:</strong>
  <%= @instant.account %>
</p>

<%= link_to 'Edit', edit_instant_path(@instant) %> |
<%= link_to 'Back', instants_path %>