config/routes.rb
Rails.application.routes.draw do

  resources :banks
  devise_for :users #, skip: [:sessions]

  root 'welcome#index'

resources :welcome do
  member do
    get '/about_us' => 'welcome#about_us'
  end

  end
  get '/subscriptions/list/' => 'subscriptions#list', as: :list_subscription
  get '/subscriptions' => 'subscriptions#index'
  get '/subscriptions/new' => 'subscriptions#new', as: :new_subscription
  get '/subscription/:id/edit' => 'subscriptions#edit', as: :edit_subscription
  get '/subscription/:id' => 'subscriptions#show', as: :subscription
  post '/subscriptions' => 'subscriptions#create'

  get '/users/:id/dash' => 'users#dash', as: :dash_user
  get '/users/:id/profile' => 'users#profile', as: :profile_user
  get 'serve' => 'users#serve', as: :serve_photo
  resources :users do

        resources :accounts do
            member do
              get 'dash' => 'accounts#dash'
              get 'display' => 'accounts/search'
              get 'search'
            end
            resources :wallets
            resources :vaults
            resources :instants do
              resources :payments
            end
          end
      end

  resources :errors do
    member do
      get 'user'
      get 'show'
      get 'delete'
      get 'notfound'# => 'errors#notfound'

    end
  end

  get 'external_pages/about_us'
  get 'external_pages/team'
  get 'external_pages/faqs'

end

app/views/partials/_footer.html.erb
<!-- footer content -->
<footer>
  <div class="pull-right">
    Momo - Hosted at PayTel - <a href="https://paytel.com">www.paytel.com</a>
  </div>
  <div class="clearfix"></div>
</footer>
<!-- /footer content -->

<div id="custom_notifications" class="custom-notifications dsp_none">
  <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
  </ul>
  <div class="clearfix"></div>
  <div id="notif-group" class="tabbed_notifications"></div>
</div>

app/views/partials/_sidenav.html.erb
<div class="main_container">

  <div class="col-md-3 left_col">
    <div class="left_col scroll-view">

      <div class="navbar nav_title" style="border: 0;">
        <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Momo!</span></a>
      </div>
      <div class="clearfix"></div>


      <!-- menu profile quick info -->
      <div class="profile">
        <div class="profile_pic">
          <%= image_tag "img.jpg", :class => "img-circle profile_img"  %>
        </div>
        <div class="profile_info">
          <span>Welcome,</span>
          <h2>Guest</h2>
        </div>
      </div>
      <!-- /menu profile quick info -->

      <br />

      <!-- sidebar menu -->
      <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

        <div class="menu_section">
          <h3> General</h3>
          <ul class="nav side-menu">
            <li><a><i class="fa fa-home"></i> About <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="index.html">Paytel</a>
                </li>
                <li><a href="index2.html">Momo</a>
                </li>
                <li><a href="index3.html">Registration</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-edit"></i> Events <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="form.html">Recruitment</a>
                </li>
                <li><a href="form_advanced.html">Roadshows</a>
                </li>
                <li><a href="form_validation.html">Scheduled Appointment</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-desktop"></i> Faq <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="general_elements.html">What is Momo?</a>
                </li>
                <li><a href="media_gallery.html">Momo Uses</a>
                </li>
                <li><a href="typography.html">General</a>
                </li>

              </ul>
            </li>
            <li><a><i class="fa fa-table"></i> News <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="tables.html">Momo in the news</a>
                </li>
                <li><a href="tables_dynamic.html">Momo for abroad</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-bar-chart-o"></i>Presentation <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="chartjs.html">Seminars</a>
                </li>
                <li><a href="chartjs2.html">Papers JS2</a>
                </li>
                <li><a href="morisjs.html">Citations JS</a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
        <div class="menu_section">
          <h3>Live Cast</h3>
          <ul class="nav side-menu">
            <li><a><i class="fa fa-bug"></i> Projects Pages <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="e_commerce.html">E-commerce</a>
                </li>
                <li><a href="projects.html">Personal</a>
                </li>
                <li><a href="project_detail.html">Charity</a>
                </li>
                <li><a href="contacts.html">Government</a>
                </li>
                <li><a href="profile.html">Corporations</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-windows"></i> Help <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="page_404.html">404 Error</a>
                </li>
                <li><a href="page_500.html">500 Error</a>
                </li>
                <li><a href="plain_page.html">Plain Page</a>
                </li>
                <li><a href="login.html">Login Page</a>
                </li>
                <li><a href="pricing_tables.html">Pricing Tables</a>
                </li>
              </ul>
            </li>
            <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> API <span class="label label-success pull-right">Coming Soon</span></a>
            <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Mobile App <span class="label label-success pull-right">Coming Soon</span></a>
            </li>
          </ul>
        </div>

      </div>
      <!-- /sidebar menu -->

      <!-- /menu footer buttons -->
      <div class="sidebar-footer hidden-small">
        <a data-toggle="tooltip" data-placement="top" title="Settings">
          <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
          <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Lock">
          <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Logout">
          <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
      </div>
      <!-- /menu footer buttons -->
    </div>
  </div>

app/views/partials/_sidenav_user.html.erb
<div class="main_container">

  <div class="col-md-3 left_col">
    <div class="left_col scroll-view">

      <div class="navbar nav_title" style="border: 0;">
        <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentellela Alela!</span></a>
      </div>
      <div class="clearfix"></div>


      <!-- menu profile quick info -->
      <div class="profile">
        <div class="profile_pic">
          <%= image_tag "img.jpg", :class => "img-circle profile_img"  %>
        </div>
        <div class="profile_info">
          <span>Welcome,</span>
          <h2><%= current_user.username %></h2>
        </div>
      </div>
      <!-- /menu profile quick info -->

      <br />

      <!-- sidebar menu -->
      <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

        <div class="menu_section">
          <h3>  </h3>
          <ul class="nav side-menu">
          </ul>
          <ul class="nav side-menu">
            <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">

                <li> <%= link_to "Profile", profile_user_path(current_user)%>
                </li>
                <li><a href="index2.html">Admin Dashboard</a>
                </li>
                <li><a href="index3.html">Monitor Dashboard</a>
                </li>
              </ul>
            </li>

            <li><a><i class="fa fa-desktop"></i> Account <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li> <%= link_to "Dashoard", dash_user_account_path(current_user,current_user.account)%>
                </li>
                <li><a href="media_gallery.html">Transfers</a>
                </li>
                <li><a href="typography.html">Contracts</a>
                </li>
                <li><a href="icons.html">Ledger</a>
                </li>
                <li><a href="inbox.html">Inbox</a>
                </li>
                <li><a href="calendar.html">Calendar</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-table"></i> Invoices <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="tables.html">Sent</a>
                </li>
                <li><a href="tables_dynamic.html">Received</a>
                </li>
                <li><a href="tables_dynamic.html">Notes</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="chartjs.html">Chart JS</a>
                </li>
                <li><a href="chartjs2.html">Chart JS2</a>
                </li>
                <li><a href="morisjs.html">Moris JS</a>
                </li>
                <li><a href="echarts.html">ECharts </a>
                </li>
                <li><a href="other_charts.html">Other Charts </a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-edit"></i> Settings <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="form.html">Profile page</a>
                </li>
                <li> <%= link_to "Personal Info", edit_user_path(current_user)%>
                </li>

                <li><%= link_to "Banks", user_account_path(current_user,current_user.account)%>
                </li>
                <li><%= link_to "Account", user_account_path(current_user,current_user.account)%>
                </li>
                <li><%= link_to "Wallets", user_account_wallets_path(current_user,current_user.account)%>
                </li>
                <li><a href="form_upload.html">Vault</a>
                </li>
                <li><a href="form_buttons.html">Contract</a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
        <div class="menu_section">
          <h3>Commerce</h3>
          <ul class="nav side-menu">
            <li><a><i class="fa fa-bug"></i> Contracts <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="e_commerce.html">Recent</a>
                </li>
                <li><a href="projects.html">Committed</a>
                </li>
                <li><a href="project_detail.html">Settled</a>
                </li>
                <li><a href="contacts.html">Pending</a>
                </li>
                <li><a href="profile.html">Cancelled</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-windows"></i> Messeges <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="page_404.html">Inbox</a>
                </li>
                <li><a href="page_500.html">Outbox</a>
                </li>
                <li><a href="plain_page.html">Sent</a>
                </li>
                <li><a href="login.html">System</a>
                </li>
                <li><a href="pricing_tables.html">Payments</a>
                </li>
              </ul>
            </li>
            <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu" style="display: none">
                <li><a href="#level1_1">Level One</a>
                <li><a>Level One<span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu" style="display: none">
                    <li class="sub_menu"><a href="level2.html">Level Two</a>
                    </li>
                    <li><a href="#level2_1">Level Two</a>
                    </li>
                    <li><a href="#level2_2">Level Two</a>
                    </li>
                  </ul>
                </li>
                <li><a href="#level1_2">Level One</a>
                </li>
              </ul>
            </li>
            <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Web Pages <span class="label label-success pull-right">Coming Soon</span></a>
            </li>
          </ul>
        </div>

      </div>
      <!-- /sidebar menu -->

      <!-- /menu footer buttons -->
      <div class="sidebar-footer hidden-small">
        <a data-toggle="tooltip" data-placement="top" title="Settings">
          <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
          <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Lock">
          <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Logout">
          <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
      </div>
      <!-- /menu footer buttons -->
    </div>
  </div>

app/views/partials/_topnav.html.erb
<!-- top navigation -->
<div class="top_nav">

    <div class="nav_menu">
      <nav class="" role="navigation">
        <div class="nav toggle">
          <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>

        <ul class="nav navbar-nav navbar-right">
          <li class="">
            <% if user_signed_in? %>
                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
              <%= image_tag "img.jpg" %> <%#= @user.email %>
                  <%= current_user.email %>

              <span class=" fa fa-angle-down"></span>
            </a>
            <ul class="dropdown-menu dropdown-usermenu pull-right">
              <li><a href="javascript:;">  Profile</a>
              </li>
              <li>
                <a href="javascript:;">
                  <span class="badge bg-red pull-right">50%</span>
                  <span>Settings</span>
                </a>
              </li>
              <li>
                <a href="javascript:;">Help</a>
              </li>
              <li>
                <a href="login.html"><i class="fa fa-sign-out pull-right"></i> Logo Out</a>
              </li>

                  <%- if controller_name != 'sessions' %>
              <li>
                <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
              </li>
                  <% end -%>

            </ul>
          </li>
                <% else %>
                <%- if controller_name != 'sessions' %>
                    <li>
                      <%= link_to 'Log in', new_user_session_path %>
                    </li>
                <% end -%>

          <% end %>


          <li role="presentation" class="dropdown">
            <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
              <i class="fa fa-envelope-o"></i>
              <span class="badge bg-green">6</span>
            </a>
            <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
              <li>
                <a>
                        <span class="image">
                                          <%= image_tag "img.jpg" %>
                                      </span>
                        <span>
                                          <span>John Smith</span>
                        <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                                          Film festivals used to be do-or-die moments for movie makers. They were where...
                                      </span>
                </a>
              </li>
              <li>
                <a>
                        <span class="image">
                                         <%= image_tag "img.jpg" %>
                                      </span>
                        <span>
                                          <span>John Smith</span>
                        <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                                          Film festivals used to be do-or-die moments for movie makers. They were where...
                                      </span>
                </a>
              </li>
              <li>
                <a>
                        <span class="image">
                                         <%= image_tag "img.jpg" %>
                                      </span>
                        <span>
                                          <span>John Smith</span>
                        <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                                          Film festivals used to be do-or-die moments for movie makers. They were where...
                                      </span>
                </a>
              </li>
              <li>
                <a>
                        <span class="image">
                                          <%= image_tag "img.jpg" %>
                                      </span>
                        <span>
                                          <span>John Smith</span>
                        <span class="time">3 mins ago</span>
                        </span>
                        <span class="message">
                                          Film festivals used to be do-or-die moments for movie makers. They were where...
                                      </span>
                </a>
              </li>
              <li>
                <div class="text-center">
                  <a>
                    <strong>See All Alerts</strong>
                    <i class="fa fa-angle-right"></i>
                  </a>
                </div>
              </li>
            </ul>
          </li>

        </ul>
      </nav>
    </div>
</div>
<!-- /top navigation -->

app/views/partials/_toptile.html.erb
<div class="top_nav">
  <div >
<!-- top tiles -->

    <!-- top tiles -->
    <div class="nav_menu">

  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="fa fa-user"></i> Total Users</span>
    <div class="count">1500</div>
    <span class="count_bottom"><i class="green">4% </i> From last Week</span>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="fa fa-clock-o"></i> Average Time</span>
    <div class="count">124.50</div>
    <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>3% </i> From last Week</span>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="fa fa-user"></i> Total Transfers</span>
    <div class="count green">7,500</div>
    <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="fa fa-user"></i> Total Business</span>
    <div class="count">4,567</div>
    <span class="count_bottom"><i class="red"><i class="fa fa-sort-desc"></i>12% </i> From last Week</span>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="fa fa-user"></i> Total Contracts</span>
    <div class="count">2,315</div>
    <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
  </div>
  <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="fa fa-user"></i> Total Connections</span>
    <div class="count">3,325</div>
    <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
  </div>

      <br>
    </div>

  </div>
</div>

<!-- /top tiles -->

app/views/partials/_welcomenavbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Start Bootstrap</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Services</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>