config/routes.rb
Rails.application.routes.draw do

  resources :banks
  devise_for :users #, skip: [:sessions]

  root 'welcome#index'

resources :welcome do
  member do
    get '/about_us' => 'welcome#about_us'
  end

  end
  get '/subscriptions/list/' => 'subscriptions#list', as: :list_subscription
  get '/subscriptions' => 'subscriptions#index'
  get '/subscriptions/new' => 'subscriptions#new', as: :new_subscription
  get '/subscription/:id/edit' => 'subscriptions#edit', as: :edit_subscription
  get '/subscription/:id' => 'subscriptions#show', as: :subscription
  post '/subscriptions' => 'subscriptions#create'

  get '/users/:id/dash' => 'users#dash', as: :dash_user
  get '/users/:id/profile' => 'users#profile', as: :profile_user
  get 'serve' => 'users#serve', as: :serve_photo
  resources :users do

        resources :accounts do
            member do
              get 'dash' => 'accounts#dash'
              get 'display' => 'accounts/search'
              get 'search'
            end
            resources :wallets
            resources :vaults
            resources :instants do
              resources :payments
            end
          end
      end

  resources :errors do
    member do
      get 'user'
      get 'show'
      get 'delete'
      get 'notfound'# => 'errors#notfound'

    end
  end

  get 'external_pages/about_us'
  get 'external_pages/team'
  get 'external_pages/faqs'

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  def list
    @subscriptions = Subscription.all
  end
  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to list_subscription_path, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:code, :name, :description, :amount, :deposit, :html, :app_url)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<body class="nav-md">
<div class="container body">
  <div class="main_container">

    <!-- page content -->
    <div class="right_col scroll-view" role="main">
      <div class="">
        <div class="page-title">
          <div class="title_left">
            <h3>Admin <small>started</small></h3>
          </div>

          <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
              </div>
            </div>
          </div>
        </div>

        <div class="clearfix"></div>
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">

                <h2>
                  <% if @subscription.new_record? %>
                  New Subscription
                  <% else %>
                      <% if @subscription.no_touching? %>
                          View Subscription
                      <% else %>
                          Update Subscription
                      <% end %>

                  <% end %>
                  <small>Admin Users</small></h2>

                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Settings 1</a>
                      </li>
                      <li><a href="#">Settings 2</a>
                      </li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>

              <div class="x_content">

            <div class="container">
              <div class="row">

                <%= form_for(@subscription) do |f| %>
                    <% if @subscription.errors.any? %>
                        <div id="error_explanation">
                          <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

                          <ul>
                            <% @subscription.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                          </ul>
                        </div>
                    <% end %>

                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                      Code
                          <%= f.text_field :code, class: "form-control" %>
                    </div>

                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                      Name    <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
                    </div>

                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                       Description   <%= f.text_area :description, rows: 7, class: "form-control", placeholder: "Description" %>
                    </div>

                      <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                        Features    <%= f.text_area :html, rows: 7, class: "form-control", placeholder: "Html" %>
                    </div>

                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    Amount <%= f.text_field :amount, class: "form-control", placeholder: "Amount" %>
                   </div>


                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                      Discount<%= f.text_field :discount, class: "form-control", placeholder: "Discount" %>
                    </div>

                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    Deposit<%= f.text_field :deposit, class: "form-control", placeholder: "Deposit" %>
                    </div>

                    <div class="col-md-3 col-sm-12 col-xs-12 form-group">
                    Mobile App url<%= f.text_field :app_url, class: "form-control", placeholder: "Mobile App Url" %>
                    </div>
                    <br>
                    <div class="clearfix"></div>
                    <div class="separator">
                      <%if @subscription.new_record? %>
                          <%= f.submit "Save", class:"btn btn-default submit" %>
                      <% else %>
                        <%if @subscription.no_touching? %>
                        <% else %>
                            <%= f.submit "Update", class:"btn btn-default submit" %>
                        <% end %>
                      <% end %>
                    </div>

                <% end %>

              </div>

            </div>
              </div>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- jQuery -->
<script src="../vendors/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="../vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="../vendors/nprogress/nprogress.js"></script>
<!-- bootstrap-daterangepicker -->
<script src="../vendors/moment/min/moment.min.js"></script>
<script src="../vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- bootstrap-datetimepicker -->
<script src="../vendors/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
<!-- Ion.RangeSlider -->
<script src="../vendors/ion.rangeSlider/js/ion.rangeSlider.min.js"></script>
<!-- Bootstrap Colorpicker -->
<script src="../vendors/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
<!-- jquery.inputmask -->
<script src="../vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js"></script>
<!-- jQuery Knob -->
<script src="../vendors/jquery-knob/dist/jquery.knob.min.js"></script>
<!-- Cropper -->
<script src="../vendors/cropper/dist/cropper.min.js"></script>

<!-- Custom Theme Scripts -->
<script src="../build/js/custom.min.js"></script>

<!-- Initialize datetimepicker -->
<script>
    $('#myDatepicker').datetimepicker();

    $('#myDateofbrth').datetimepicker({
        format: 'DD.MM.YYYY'
    });

    $('#myDatepicker3').datetimepicker({
        format: 'hh:mm A'
    });

    $('#myDatepicker4').datetimepicker({
        ignoreReadonly: true,
        allowInputToggle: true
    });

    $('#datetimepicker6').datetimepicker();

    $('#datetimepicker7').datetimepicker({
        useCurrent: false
    });

    $("#datetimepicker6").on("dp.change", function(e) {
        $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
    });

    $("#datetimepicker7").on("dp.change", function(e) {
        $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
    });
</script>

app/views/subscriptions/edit.html.erb
<%= render 'form' %>

app/views/subscriptions/index.html.erb
<body class="nav-md">
<div class="container body">
  <div class="main_container">

    <!-- page content -->
    <div class="right_col scroll-view" role="main">

    <!-- page content -->

      <div class="">
        <div class="page-title">
          <div class="title_left">
            <h3>Subscription</h3>
          </div>

          <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">

            </div>
          </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel" style="height:600px;">
              <div class="x_title">
                <h2>Service subscriptions</h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Settings 1</a>
                      </li>
                      <li><a href="#">Settings 2</a>
                      </li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>

              <div class="x_content">
                <div class="row">

                  <div class="col-md-12">
                    <% @subscriptions.each do |subscription| %>
                    <% if subscription.discount==0 %>
                        <!-- price element -->
                        <div class="col-md-3 col-sm-6 col-xs-12">
                      <div class="pricing">
                        <div class="title">
                          <h2><%= subscription.name %></h2>
                          <h1>
                            <%if subscription.amount==0 %>
                                free
                                <% else%>
                                <%= subscription.amount %>
                                <% end %>
                          </h1>
                        </div>
                        <div class="x_content">
                          <div class="">
                            <div class="pricing_features">
                              <ul class="list-unstyled text-left">
                                <%= subscription.html.html_safe %>
                              </ul>
                            </div>
                          </div>
                          <div class="pricing_footer">
                            <a href="javascript:void(0);" class="btn btn-success btn-block" role="button">Download <span> now!</span></a>
                            <p>
                              <a href="javascript:void(0);"> <%= link_to 'Sign up', new_user_registration_path %></a>
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- price element -->
                      <% else %>
                        <!-- price element -->
                        <div class="col-md-3 col-sm-6 col-xs-12">
                          <div class="pricing ui-ribbon-container">
                            <div class="ui-ribbon-wrapper">
                              <div class="ui-ribbon">
                                <%= subscription.discount %>% Off
                              </div>
                            </div>
                            <div class="title">
                              <h2><%= subscription.name %></h2>
                              <h1>
                                <%if subscription.amount==0 %>
                                    free
                                <% else%>
                                    <%= subscription.amount %>
                                <% end %>
                              </h1>
                              <span>Monthly</span>
                            </div>
                            <div class="x_content">
                              <div class="">
                                <div class="pricing_features">
                                  <ul class="list-unstyled text-left">
                                    <%= subscription.html.html_safe %>
                                  </ul>
                                </div>
                              </div>
                              <div class="pricing_footer">
                                <a href="javascript:void(0);" class="btn btn-primary btn-block" role="button">Download <span> now!</span></a>
                                <p>
                                  <a href="javascript:void(0);"> <%= link_to 'Sign up', new_user_registration_path %></a>
                                </p>
                              </div>
                            </div>
                          </div>
                        </div>
                        <!-- price element -->
                    <% end %>
                    <% end %>

       </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    <!-- /page content -->
  </div>
</div>
</div>
<!-- jQuery -->
<script src="../vendors/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="../vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="../vendors/nprogress/nprogress.js"></script>

<!-- Custom Theme Scripts -->
<script src="../build/js/custom.min.js"></script>
</body>

app/views/subscriptions/list.html.erb
<body class="nav-md">
<div class="container body">
  <div class="main_container">

    <!-- page content -->
    <div class="right_col scroll-view" role="main">
      <div class="">
        <div class="page-title">
          <div class="title_left">
            <h3>Admin <small>started</small></h3>
          </div>

          <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
              </div>
            </div>
          </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>Listing Subscriptions<small><%= link_to 'New Subscription', new_subscription_path %></small></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Settings 1</a>
                      </li>
                      <li><a href="#">Settings 2</a>
                      </li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <p class="text-muted font-13 m-b-30">
                  Responsive Admin extension for different screen sizes through the dynamic insertion and removal of columns.
                </p>

                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                  <thead>
                  <tr>
                    <th>Code</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Amount</th>
                    <th>Discount</th>
                    <th>Deposit</th>
                    <th>Html</th>
                    <th>App url</th>
                    <th colspan="4"></th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @subscriptions.each do |subscription| %>
                      <tr>
                        <td><%= subscription.code %></td>
                        <td><%= subscription.name %></td>
                        <td><%= subscription.description %></td>
                        <td><%= subscription.amount %></td>
                        <td><%= subscription.discount %></td>
                        <td><%= subscription.deposit %></td>
                        <td><%= subscription.html.html_safe %></td>
                        <td><%= subscription.app_url %></td>
                        <td><%= link_to 'New', new_subscription_path %></td>
                        <td><%= link_to 'Show', subscription %></td>
                        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
                        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      </tr>
                      <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /page content -->

  </div>
</div>

</body>




<br>

app/views/subscriptions/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<body class="nav-md">
<div class="container body">
  <div class="main_container">

    <!-- page content -->
    <div class="right_col" role="main">
      <div class="">
        <div class="page-title">
          <div class="title_left">
            <h3>Subscription</h3>
          </div>

          <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
              </div>
            </div>
          </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel" style="height:600px;">
              <div class="x_title">
                <h2>Service subscriptions</h2>  <%= link_to '  Back', list_subscription_path %>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Settings 1</a>
                      </li>
                      <li><a href="#">Settings 2</a>
                      </li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>

              <div class="x_content">
                <div class="row">

                  <div class="col-md-12">

                        <% if @subscription.discount==0 %>
                            <!-- price element -->
                            <div class="col-md-3 col-sm-6 col-xs-12">
                              <div class="pricing">
                                <div class="title">
                                  <h2><%= @subscription.name %></h2>
                                  <h1>
                                    <%if @subscription.amount==0 %>
                                        free
                                    <% else%>
                                        <%= @subscription.amount %>
                                    <% end %>
                                  </h1>
                                </div>
                                <div class="x_content">
                                  <div class="">
                                    <div class="pricing_features">
                                      <ul class="list-unstyled text-left">
                                        <%= @subscription.html.html_safe %>
                                      </ul>
                                    </div>
                                  </div>
                                  <div class="pricing_footer">
                                    <a href="javascript:void(0);" class="btn btn-success btn-block" role="button">Download <span> now!</span></a>
                                    <p>
                                      <a href="javascript:void(0);"> <%= link_to 'Sign up', new_user_registration_path %></a>                                    </p>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <!-- price element -->
                        <% else %>
                            <!-- price element -->
                            <div class="col-md-3 col-sm-6 col-xs-12">
                              <div class="pricing ui-ribbon-container">
                                <div class="ui-ribbon-wrapper">
                                  <div class="ui-ribbon">
                                    <%= @subscription.discount %>% Off
                                  </div>
                                </div>
                                <div class="title">
                                  <h2><%= @subscription.name %></h2>
                                  <h1>
                                    <%if @subscription.amount==0 %>
                                        free
                                    <% else%>
                                        <%= @subscription.amount %>
                                    <% end %>
                                  </h1>
                                  <span>Monthly</span>
                                </div>
                                <div class="x_content">
                                  <div class="">
                                    <div class="pricing_features">
                                      <ul class="list-unstyled text-left">
                                        <%= @subscription.html.html_safe %>
                                      </ul>
                                    </div>
                                  </div>
                                  <div class="pricing_footer">
                                    <a href="javascript:void(0);" class="btn btn-primary btn-block" role="button">Download <span> now!</span></a>
                                    <p>
                                      <a href="javascript:void(0);">Sign up</a>
                                    </p>
                                  </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <!-- price element -->
                        <% end %>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>
    <!-- /page content -->

  </div>
</div>

<!-- jQuery -->
<script src="../vendors/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="../vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="../vendors/nprogress/nprogress.js"></script>

<!-- Custom Theme Scripts -->
<script src="../build/js/custom.min.js"></script>
</body>

app/views/subscriptions/show2.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @subscription.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @subscription.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @subscription.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @subscription.amount %>
</p>

<p>
  <strong>Deposit:</strong>
  <%= @subscription.deposit %>
</p>

<p>
  <strong>Html:</strong>
  <%= @subscription.html %>
</p>

<p>
  <strong>App url:</strong>
  <%= @subscription.app_url %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>