config/routes.rb
Rails.application.routes.draw do

  resources :banks
  devise_for :users #, skip: [:sessions]

  root 'welcome#index'

resources :welcome do
  member do
    get '/about_us' => 'welcome#about_us'
  end

  end
  get '/subscriptions/list/' => 'subscriptions#list', as: :list_subscription
  get '/subscriptions' => 'subscriptions#index'
  get '/subscriptions/new' => 'subscriptions#new', as: :new_subscription
  get '/subscription/:id/edit' => 'subscriptions#edit', as: :edit_subscription
  get '/subscription/:id' => 'subscriptions#show', as: :subscription
  post '/subscriptions' => 'subscriptions#create'

  get '/users/:id/dash' => 'users#dash', as: :dash_user
  get '/users/:id/profile' => 'users#profile', as: :profile_user
  get 'serve' => 'users#serve', as: :serve_photo
  resources :users do

        resources :accounts do
            member do
              get 'dash' => 'accounts#dash'
              get 'display' => 'accounts/search'
              get 'search'
            end
            resources :wallets
            resources :vaults
            resources :instants do
              resources :payments
            end
          end
      end

  resources :errors do
    member do
      get 'user'
      get 'show'
      get 'delete'
      get 'notfound'# => 'errors#notfound'

    end
  end

  get 'external_pages/about_us'
  get 'external_pages/team'
  get 'external_pages/faqs'

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :wallets, dependent: :delete_all
  has_many :instants, dependent: :delete_all
  has_many :vaults, dependent: :delete_all

  def self.search(search)
    where("Oid = ?", "%#{search}%")
    #where("content LIKE ?", "%#{search}%")
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  #before_action :set_user
  before_action :set_account, only: [:show, :dash, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  def list
    @accounts = Account.all
    if params[:account_reference]
      @account = Account.find(params[:account_reference])
    else
      #@staff = Staff.find(params[:search])
      @accounts = Account.all.order("account_reference DESC")
    end

  end

  def dash
    #@user = current_user
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show

  end

  def search

    if params[:search]
      @account = params[:search]
      #@staff = Staff.search(params[:search])
    else
      @account = Account.find(params[:search])
    end
  end

  # GET /accounts/new
  def new
    #@account = Account.new
    @account = @user.account.build
    @account.account_reference = @user.account_reference
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
   # @account = Account.new(account_params)
    @account =@user.accounts.build(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to [@user,@account], notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:user_id])
    #rescue ActiveRecord::RecordNotFound
    #respond_to do |format|
      #format.html { redirect_to errors_user_path, notice: 'User not found.' }
      #format.json { head :no_content}
    #end

 # rescue ActiveRecord::RecordNotFound
  #  flash[:alert] = "User not found."
   # redirect_to errors_user_path
  end


    def set_account
      @account = Account.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      respond_to do |format|
        format.html { redirect_to errors_notfound_path, notice: 'Account not found.' }
        format.json { head :no_content}
        render users_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:Oid, :account_reference, :name, :balance, :blocked, :date_blocked, :expired, :date_of_expiry, :bank, :user_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper

end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Oid %><br>
    <%= f.text_field :Oid %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :balance %><br>
    <%= f.text_field :balance %>
  </div>
  <div class="field">
    <%= f.label :blocked %><br>
    <%= f.check_box :blocked %>
  </div>
  <div class="field">
    <%= f.label :date_blocked %><br>
    <%= f.datetime_select :date_blocked %>
  </div>
  <div class="field">
    <%= f.label :expired %><br>
    <%= f.check_box :expired %>
  </div>
  <div class="field">
    <%= f.label :date_of_expiry %><br>
    <%= f.date_select :date_of_expiry %>
  </div>
  <div class="field">
    <%= f.label :bank %><br>
    <%= f.text_field :bank %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/_search_form.html.erb
<div class="span2">
</div>
<div class="span10">
  <div class="module">
    <div class="module-head">
      <h3>Profile: <%= @staff.last_name << ", " << @staff.first_name << " " << @staff.middle_name %></h3>


    </div>

  </div>

</div>

app/views/accounts/_wizform.html.erb
<%#= form_for(@account) do |f| %>

<%= form_for([@account], html: { class:"form-horizontal row-fluid" }) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Oid %><br>
    <%= f.text_field :Oid %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :balance %><br>
    <%= f.text_field :balance %>
  </div>
  <div class="field">
    <%= f.label :blocked %><br>
    <%= f.check_box :blocked %>
  </div>
  <div class="field">
    <%= f.label :date_blocked %><br>
    <%= f.datetime_select :date_blocked %>
  </div>
  <div class="field">
    <%= f.label :expired %><br>
    <%= f.check_box :expired %>
  </div>
  <div class="field">
    <%= f.label :date_of_expiry %><br>
    <%= f.date_select :date_of_expiry %>
  </div>
  <div class="field">
    <%= f.label :bank %><br>
    <%= f.text_field :bank %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<body class="nav-md">
<div class="container body">
  <div class="main_container">


    <!-- page content -->
    <div class="right_col" role="main">
      <div class="">
        <div class="page-title">
          <div class="title_left">
            <h3>User Listing</h3>
          </div>

          <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
              </div>
            </div>
          </div>
        </div>

        <div class="clearfix"></div>

        <div class="row scroll-view">

          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>Responsive look<small><%= link_to 'New Account', new_user_account_path(:user) %></small></h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#">Settings 1</a>
                      </li>
                      <li><a href="#">Settings 2</a>
                      </li>
                    </ul>
                  </li>
                  <li><a class="close-link"><i class="fa fa-close"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                <p class="text-muted font-13 m-b-30">
                  Responsive Admin extension for Admins only.
                </p>

                <table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">

                  <thead>
                  <tr>
                    <th>Reference</th>
                    <th>Name</th>
                    <th>Balance</th>
                    <th>Blocked</th>
                    <th>Date blocked</th>
                    <th>Expired</th>
                    <th>Date of expiry</th>
                    <th>Bank</th>
                    <th colspan="3"></th>
                  </tr>
                  </thead>


                  <div class="col-md-4 hidden-small">

                    <tbody>
                    <% @accounts.each do |account| %>
                        <tr>

                          <td><%= link_to account.account_reference %></td>
                          <td><%= account.name %></td>
                          <td><%= account.balance %></td>
                          <td><%= account.blocked %></td>
                          <td><%= account.date_blocked %></td>
                          <td><%= account.expired %></td>
                          <td><%= account.date_of_expiry %></td>
                          <td><%= account.bank %></td>
                          <td></td>
                          <td><%#= link_to 'Edit', edit_account_path(account) %></td>
                          <td><%#= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                    <% end %>

                    </tbody>
                  </div>
                </table>


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /page content -->


</div>

<!-- jQuery -->
<script src="../vendors/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="../vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="../vendors/nprogress/nprogress.js"></script>
<!-- iCheck -->
<script src="../vendors/iCheck/icheck.min.js"></script>
<!-- Datatables -->
<script src="../vendors/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="../vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script src="../vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="../vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
<script src="../vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
<script src="../vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
<script src="../vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
<script src="../vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
<script src="../vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
<script src="../vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
<script src="../vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
<script src="../vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
<script src="../vendors/jszip/dist/jszip.min.js"></script>
<script src="../vendors/pdfmake/build/pdfmake.min.js"></script>
<script src="../vendors/pdfmake/build/vfs_fonts.js"></script>

<!-- Custom Theme Scripts -->
<script src="../build/js/custom.min.js"></script>

</body>


<!--Test Page specific JS -->
<script> alert ('You are logged into accounts')</script>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/search.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="span2">
        <div class="sidebar">
          <%#= render "staffs/main_staff_menu"%>
        </div>
      </div>


      <%= form_tag(@acount, :method => "get", id: "search-form", html_options: {class: "navbar-search pull-left input-append"}) do |f| %>
          <%= text_field_tag :search, params[:search], placeholder: "Search by Staff file" %>
          <%= button_tag("", class: ["btn", "icon-search"]) %>
      <% end %>

      <% if @account.present? %>
          <%= render @account %>
      <% else %>
          <p>There are no staff with the term(s) <%= params[:search] %>.</p>
      <% end %>


    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<body class="nav-md">

<div class="container body">
  <div class="main_container">
    <div class="right_col" role="main">

    <p id="notice"><%= notice %></p>
<% if @account.nil? %>
    # flash[:warn ] = "Account not found, create one using the button below.."
    <button class="btn btn-default source" onclick="new PNotify({
        title: 'Non-Blocking Notice',
        type: 'info',
        text: 'When you hover over me I\'ll fade to show the elements underneath. Feel free to click any of them just like I wasn\'t even here.',
        nonblock: {
            nonblock: true
            },
        styling: 'bootstrap3',
        addclass: 'dark'
        });">Non-Blocking Notice</button>

    <hr />

    <%= link_to 'Create New Account', new_account_path %>

    <% else %>
    <p>
      <strong>Oid:</strong>
      <%= @account.Oid %>
    </p>

    <p>
      <strong>Code:</strong>
      <%= @account.account_reference %>
    </p>

    <p>
      <strong>Name:</strong>
      <%= @account.name %>
    </p>

    <p>
      <strong>Balance:</strong>
      <%= @account.balance %>
    </p>

    <p>
      <strong>Blocked:</strong>
      <%= @account.blocked %>
    </p>

    <p>
      <strong>Date blocked:</strong>
      <%= @account.date_blocked %>
    </p>

    <p>
      <strong>Expired:</strong>
      <%= @account.expired %>
    </p>

    <p>
      <strong>Date of expiry:</strong>
      <%= @account.date_of_expiry %>
    </p>

    <p>
      <strong>Bank:</strong>
      <%= @account.bank %>
    </p>



    <%= link_to 'Edit', edit_user_account_path(:user,:account) %> |
    <%= link_to 'Back', user_accounts_path %>
<% end %>
<!-- PNotify -->
<script src="../vendors/pnotify/dist/pnotify.js"></script>
<script src="../vendors/pnotify/dist/pnotify.buttons.js"></script>
<script src="../vendors/pnotify/dist/pnotify.nonblock.js"></script>

  </div>
  </div>
</div>
</body>